esphome:
  name: uart-readline-example
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "YourSSID"
  password: "YourPassword"

logger:
  level: DEBUG

api:

ota:

# External component configuration
external_components:
  - source:
      type: local
      path: components

# UART configuration
uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

# UART ReadLine Text Sensor
text_sensor:
  - platform: uart_readline
    name: "UART Line Data"
    uart_id: uart_bus
